Category functionality added
minetest-mods/unified_inventory pull request #171
Opened 2021-03-29 02:15 UTC by oversword

Fixes #170 

- Added API for configuring categories
- Added display for categories above page
- Reduced height of page by 1 row to make room for categories
- Added L/R scroll through when there are more categories than columns
- Added pre-filter methods for categories and uncategorised items
- Added categories for (most) items in the default game

2021-03-29 02:15 UTC, oversword commented
I have noticed this has odd behaviour with groups, it should reset the category to "all" when a group is filtered

2021-03-29 23:37 UTC, VanessaE commented
It seems to work, but I have a number of comments on the visuals:

* For a moment after starting, I thought nothing had changed other than some obscure sorting.  You need to add some details that make it clear that the upper row is categories now.  You might consider moving the categories row up, putting the "Filter" and search pattern below it (perhaps on one line in "full" and two lines in "lite" mode), then drawing a box around the categories and labeling that section accordingly.
* The misc button is...not right.  Where I live, the "no" symbol makes that button look like is says "don't click me, I'll blow up" :grin:  However, you may have noticed `ui_group.png` in the textures folder, which I think is unused.  Its made of nodes not in the "misc" category, so here is a variation on it that should be perfect for the "misc" button:
  ![image](https://user-images.githubusercontent.com/1733537/112906389-1b397800-90ba-11eb-9680-3b1a130d9341.png)
  <sub>Scaled down from an in-game screenshot for authenticity.</sub>
  <sup>All nodes depicted there are present in `minetest_game` and are in the misc. category.</sup>
* The forward/back buttons should be side by side, similar to the buttons below the search bar.  Perhaps put them both at the far right.
* The image used for the "All" button is misleading. When used for the clear search button, it's meant to suggest to "sweep away" the user's search terms. After some googling, it seems like a favored depiction of "show all" is a square with some horizontal lines on it, with an eye overlapping it (as if to suggest "looking at a page of text").  I don't think an eye is a good idea, and a grid would make more sense than lines, so here's my take on it:
  ![image](https://user-images.githubusercontent.com/1733537/112911013-88e9a200-90c2-11eb-95c7-0e0dadca2448.png)
  <sub>It isn't obvious here, but there is an 8-pixel transparent edge around it.</sub>
* For the minerals category button, I would suggest using the iron lump, it's more of a mineral than a Mese crystal. :smile:

2021-03-29 23:38 UTC, VanessaE reviewed
It seems to work, but I have a number of comments on the visuals:

* For a moment after starting, I thought nothing had changed other than some obscure sorting.  You need to add some details that make it clear that the upper row is categories now.  You might consider moving the categories row up, putting the "Filter" and search pattern below it (perhaps on one line in "full" and two lines in "lite" mode), then drawing a box around the categories and labeling that section accordingly.
* The misc button is...not right.  Where I live, the "no" symbol makes that button look like is says "don't click me, I'll blow up" :grin:  However, you may have noticed `ui_group.png` in the textures folder, which I think is unused.  Its made of nodes not in the "misc" category, so here is a variation on it that should be perfect for the "misc" button:
  ![image](https://user-images.githubusercontent.com/1733537/112906389-1b397800-90ba-11eb-9680-3b1a130d9341.png)
  <sub>Scaled down from an in-game screenshot for authenticity.</sub>
  <sup>All nodes depicted there are present in `minetest_game` and are in the misc. category.</sup>
* The forward/back buttons should be side by side, similar to the buttons below the search bar.  Perhaps put them both at the far right.
* The image used for the "All" button is misleading. When used for the clear search button, it's meant to suggest to "sweep away" the user's search terms. After some googling, it seems like a favored depiction of "show all" is a square with some horizontal lines on it, with an eye overlapping it (as if to suggest "looking at a page of text").  I don't think an eye is a good idea, and a grid would make more sense than lines, so here's my take on it:
  ![image](https://user-images.githubusercontent.com/1733537/112911013-88e9a200-90c2-11eb-95c7-0e0dadca2448.png)
  <sub>It isn't obvious here, but there is an 8-pixel transparent edge around it.</sub>
* For the minerals category button, I would suggest using the iron lump, it's more of a mineral than a Mese crystal. :smile:

2021-03-30 00:16 UTC, oversword commented
Great notes @VanessaE , I will submit some changes tomorrow

I had tried to make the top row more obvious via spacing, but after realising rows were not a full 1 unit large I noticed my alignment was different to the original and I didn't have as much space to play with as I thought.

Putting it above the filter is a good suggestion, I originally tried squashing the filter down to one line to make a bit more room for spacing, what do you think? I don't see the need for it to be on 2 lines, we can just concatenate the text as far as I see...

How would I go about "drawing a box around the categories"? Formspec is a nightmare and I'm really just modifying examples I've seen, so any help there is appreciated.

Thanks for the graphics, I will see how they look scaled down and put them to use, I was just trying to avoid creating new icons as it's hard to fit the theme with this mod and it's not my strong suit

Other suggestions will be taken to heart, I'll ping you tomorrow when it's ready to take another look :)

2021-03-30 01:37 UTC, VanessaE commented
> Putting it above the filter is a good suggestion, I originally tried squashing the filter down to one line to make a bit more room for spacing, what do you think? I don't see the need for it to be on 2 lines, we can just concatenate the text as far as I see...

I only kept it as 2 lines during the formspec v4 rewrite for consistency, but I don't actually see any reason for it to not be one line.  A user could theoretically give a search string that would make it overflow the formspec, but even in "lite" mode it would have to be ridiculously long.

Let's put both on one line.

> How would I go about "drawing a box around the categories"? Formspec is a nightmare and I'm really just modifying examples I've seen, so any help there is appreciated.

The simplest way would be to put a `background9[]` formspec element behind your categories bar (by putting it first in the formspec string), with a size appropriate to cover the area used by the buttons.  You could tell it to use UI's standard formspec background image if you want, but the borders on it are probably a little too thick for this purpose.

> Thanks for the graphics, I will see how they look scaled down and put them to use, I was just trying to avoid creating new icons as it's hard to fit the theme with this mod and it's not my strong suit

I guess you mean "shown at normal in-game size" rather than "scaled-down".  UI uses 128px icons as standard, so that they'll render reasonably cleanly even on 4k or so-called "retina" screens.

2021-03-30 01:59 UTC, oversword commented
> I guess you mean "shown at normal in-game size" rather than "scaled-down"

Well I'm seeing it rendered at about 48x48px on a normal resolution screen, it will be smaller in lite mode, I just mean to make sure they are meaningful when at that size

2021-03-30 02:44 UTC, VanessaE commented
> > I guess you mean "shown at normal in-game size" rather than "scaled-down"
> 
> Well I'm seeing it rendered at about 48x48px on a normal resolution screen, it will be smaller in lite mode, I just mean to make sure they are meaningful when at that size

They will be.  You don't have to worry about resolution; just use the images as they are.  This is one of the few places in Minetest that Simply Just Works™. :smile:

2021-03-30 02:48 UTC, VanessaE commented
![image](https://user-images.githubusercontent.com/1733537/112926008-ce1ccc80-90e0-11eb-9aea-18d167d9d5ad.png)

2021-03-30 02:50 UTC, VanessaE commented
Oh I must have been thinking of image slots.  A normal size button is 51px on my screen.  So you *could* get away with a 64px base image if you're targeting a normal screen, but that would still negatively impact 4k/"retina" users.

2021-03-31 02:41 UTC, oversword commented
@VanessaE I've made those updates, however I decided against the background as I was having trouble sizing the `background9` element. I think it looks okay simply separated from the main page by the filter text, but I can take another shot at it if you still think it's necessary.

2021-03-31 04:29 UTC, VanessaE commented
I don't know how to add a commit such that it'll appear as added onto your PR here, so here's a patch to add the border:
```patch
commit 0dbe1fba02c45e62caa687c0b5d6f10355902f1e (HEAD -> master)
Author: Vanessa Dannenberg <vanessa.e.dannenberg@gmail.com>
Date:   Wed Mar 31 00:13:21 2021 -0400

    add border around categories

diff --git a/internal.lua b/internal.lua
index 2976bcb..ad5fc18 100644
--- a/internal.lua
+++ b/internal.lua
@@ -60,18 +60,17 @@ function ui.get_formspec(player, page)
 		pagedef.formspec_prepend and "" or "no_prepend[]",
 		ui.standard_background -- Background
 	}
-	local n = 4
 
 	if draw_lite_mode then
 		formspec[1] = "formspec_version[4]size[14,9.75]"
-		formspec[3] = ui.standard_background
 	end
 
 	local perplayer_formspec = ui.get_per_player_formspec(player_name)
 	local fsdata = pagedef.get_formspec(player, perplayer_formspec)
 
-	formspec[n] = fsdata.formspec
-	n = n+1
+	formspec[4] = fsdata.formspec
+
+	local n = 5
 
 	local button_row = 0
 	local button_col = 0
@@ -129,11 +128,22 @@ function ui.get_formspec(player, page)
 	local categories_scroll_pos = { ui_peruser.page_x, ui_peruser.page_y-(ui_peruser.btn_spc*0.15)-0.7 }
 
 	local scroll_offset = 0
+	local sizey = 1.2
+	local xoffs = 0.07
+	local yoffs = 0.03
+
 	local category_count = #unified_inventory.category_list
 	if category_count > ui_peruser.pagecols then
 		scroll_offset = unified_inventory.current_category_scroll[player_name]
+		sizey = 2.05
+		yoffs = 0.06
 	end
 
+	formspec[n] = string.format("background9[%f,%f;%f,%f;ui_catbg_9_sliced.png;false;16]",
+					ui_peruser.page_x - xoffs, ui_peruser.page_y - yoffs - ui_peruser.btn_spc - ui_peruser.btn_size,
+					ui_peruser.btn_spc*ui_peruser.pagecols + 0.05, ui_peruser.btn_size*sizey)
+	n = n + 1
+
 	for index, category in ipairs(unified_inventory.category_list) do
 		local column = index - scroll_offset
 		if column > 0 and column <= ui_peruser.pagecols then
diff --git a/textures/ui_catbg_9_sliced.png b/textures/ui_catbg_9_sliced.png
new file mode 100644
index 0000000..1a08d68
Binary files /dev/null and b/textures/ui_catbg_9_sliced.png differ
```
And the image it uses:
![ui_catbg_9_sliced](https://user-images.githubusercontent.com/1733537/113090557-0e02b300-91b8-11eb-9606-88988b44fcdf.png)

2021-03-31 04:31 UTC, VanessaE commented
I've added your PR to a new branch here on UI upstream, `categories`, with the above patch applied on top of it, to make it easier to work on.

2021-03-31 04:45 UTC, VanessaE commented
Minor heads-up: I force-pushed to that branch to get rid of an unrelated change, and updated the above-pasted patch

2021-03-31 05:05 UTC, VanessaE commented
A couple of notes about my addition:

* In UI's "lite" mode, "Filter: blah blah" ends up inside the categories box, because I had to make the box two "rows" tall to enclose the previous/next buttons.  I'm not sure how I feel about this arrangement:
![image](https://user-images.githubusercontent.com/1733537/113093055-2923f180-91bd-11eb-8717-a0293e52101e.png)

* Getting the border's positioning and size right required a couple of hard-coded "magic" numbers (as opposed to using maths against UI's button-related variables).  It works, but I'm not sure I"m happy with this, either.

But neither of those are your doing. :smile:

2021-03-31 09:58 UTC, oversword commented
I was considering putting the arrows above the category list to avoid overlapping the filter, but then it looks like that's the page turn arrows

As per the box I was thinking maybe a second box could go around the arrows with the top removed so it "merges" with the second one...

I have some ideas about re-arrangement, let me make a mock up quickly and show you

2021-03-31 10:13 UTC, oversword commented
@VanessaE How about something like this? It would be much easier to put the box around it then
![ui-mockup](https://user-images.githubusercontent.com/1569128/113128757-0c65d900-9212-11eb-9fe1-2a1b573b8e12.png)

2021-03-31 13:03 UTC, VanessaE commented
That layout looks good.  As for the page number, as far as I know, most all elements can be moved depending on lite or full mode.

2021-03-31 13:05 UTC, VanessaE commented
As for a two-part box (which would then be L-shaped, there's no option for that other than a single large image. I would not recommend that.

2021-04-01 02:18 UTC, oversword commented
@VanessaE that's all done now, I did the container background in a separate commit in case we want to revert it because I think it's pretty clear without it ant this point. Let me know what you think

IDK how the linting is suddenly failing, line 57 is not changed and has no whitespace, I've seen your latest commit is failing this check too so I hope that's okay

2021-04-01 02:30 UTC, VanessaE commented
Yeah I saw that warning and disregarded it.  The linter can go ge.....ahem, can be safely ignored in this case. :wink:

Full mode seems fine.

For lite mode, I recommend reducing the gap between the search widget/buttons and the page contents, and use some of that "savings" to add a bit of a margin above the categories box and below the page count.  

The box seems a little taller than it needs to be, in both modes, so if you shrink it a little, that'll help in the case of those margins

2021-04-01 22:38 UTC, oversword commented
@VanessaE The spacings for lite mode have been adjusted, I think that's looking a bit better

2021-04-02 00:50 UTC, VanessaE commented on internal.lua
> +		ui_peruser.page_x-0.1, categories_scroll_pos[1],
This broke it.  You're now using an X coordinate in the spot for the Y coordinate.  Did you mean `categories_scroll_pos[2]` ?

2021-04-02 01:02 UTC, oversword commented on internal.lua
> +		ui_peruser.page_x-0.1, categories_scroll_pos[1],
Eep sorry forgot it was one-indexed and didn't give it a test

2021-04-02 01:03 UTC, oversword commented on internal.lua
> +		ui_peruser.page_x-0.1, categories_scroll_pos[1],
I was just consolidating a few vars

2021-04-02 01:06 UTC, oversword commented on internal.lua
> +		ui_peruser.page_x-0.1, categories_scroll_pos[1],
Fixed

2021-04-02 03:26 UTC, VanessaE commented
The box is in the right place now, though I still think it's too tall:
![image](https://user-images.githubusercontent.com/1733537/113377238-bee88980-9341-11eb-90ed-1ec430958c28.png)

2021-04-02 03:54 UTC, oversword commented
> The box is in the right place now, though I still think it's too tall in full mode:

It makes more sense when the arrows are there, try adding another category or 2 from a custom mod or just in the `default-categories.lua` file if you remember to undo it... I'll get you a screenshot

2021-04-02 04:20 UTC, VanessaE commented
Oh right, I didn't think about that.  Maybe move the "Categories" label up close to the top of the box then? (both modes)

2021-04-02 05:19 UTC, oversword commented
> Maybe move the "Categories" label up close to the top of the box then? (both modes)

Are you sure? I kind of intentionally centred that with the arrows because I thought it looked better. I think in most scenarios besides the default config there will be more than 8 categories and the arrows will appear, for instance "automation" and "food" are probably categories that everyone will have on their servers, but with the default mods all we have is the furnace and apples so no need for categories

2021-04-02 05:40 UTC, VanessaE commented
Perhaps you're right.  Though bear in mind that that last image I posted was from Dreambuilder (which is also why it's a lightly-colored theme).  Guess @tenplus1 needs to add farming redo's foods to that category, and I suppose I should put Pipeworks' stuff in automation.  Who gets to update Technic? :)

2021-04-02 06:00 UTC, oversword commented
>  Who gets to update Technic? 😁

Oof it'll be a big job for sure, I intend to go through the mods that BLS has and add categories into the custom mod, others should be able to copy from that but I do not fancy the task of updating each mod individually and getting the PR through, for the most part a server should be able to just take a list of all the nodes and copy+paste them into categories in chunks by mod

Notice this code I left commented out at the bottom of `default_categories.lua`
```
minetest.after(5, function ( )
	local l = {}
	for name,_ in pairs(minetest.registered_items) do
		if not unified_inventory.find_category(name) then
			table.insert(l, name)
		end
	end
	table.sort(l)
	minetest.log(table.concat(l, '",'.."\n"..'"'))
end)
```
That should basically dump out a usable & sorted list of currently uncategorised nodes

2021-04-02 08:08 UTC, VanessaE commented
Well Pipeworks is ready for when this PR goes in :smile:

2021-04-02 08:11 UTC, VanessaE commented
I guess this PR is ready to merge.  @SmallJoker any remarks?

2021-04-02 08:14 UTC, VanessaE approved these changes

2021-04-02 17:02 UTC, SmallJoker requested changes
The PR works and looks good in concept, but the hardcoded items would need too much maintenance to be helpful. Please add them automatically using tool/item/node definition checks.

Also: Are the textures png-crushed/optipng'd yet?

2021-04-02 17:02 UTC, SmallJoker commented on internal.lua
> +		formspec[n] = formspec_button(ui_peruser, "next_category", "ui_right_icon.png", categories_scroll_pos, {ui_peruser.pagecols - 1, 0}, 0.8, "Scroll Categories Right")
User-facing strings should be translated. i.e.  `S("Scroll Categories Left")`

Lines way too long. Please keep them at reasonable length.

2021-04-02 17:02 UTC, SmallJoker commented on internal.lua
> +			and def.description ~= ""
These lines are repetitive. Please move them to `ffilter` or a separate function to avoid code duplication.

2021-04-02 21:54 UTC, oversword commented on internal.lua
> +		formspec[n] = formspec_button(ui_peruser, "next_category", "ui_right_icon.png", categories_scroll_pos, {ui_peruser.pagecols - 1, 0}, 0.8, "Scroll Categories Right")
All labels are translated, see line 39

I opted for the longer names to match the clarity of the arrow buttons at the bottom, reading "Back one page" and "Forward one page" I do not see the need to sacrifice clarity for size

2021-04-02 22:01 UTC, oversword commented on category.lua
> +end
This is for when you want to manually remove an item from a category because you do not feel it belongs there / you have added a new category for it to go into and do not want any overlap. It doesn't matter if items have been removed from the game, the logic on lines 319-350 excludes items that do not exist from being displayed, as well as something in the rendering step I believe

2021-04-02 22:08 UTC, oversword commented on default-categories.lua
> +	"default:sword_diamond",
I will add in a config option for automatic categories, but I think for most people it would be an annoyance to have the mod making assumptions based on someone else's logic. Hard coding these items is no issue because they all appear in the base game, and there is no problem if an items does not exist. Theoretically we could manually list all the items of other mods within this mod itself, without depending on those mods. The way this works does not depend on a mod or item being loaded or existing to give the expected result. For this proof of concept MR I thought it was appropriate to only add the items that appear in the default mods.

2021-04-02 22:34 UTC, oversword commented on callbacks.lua
> +	unified_inventory.current_category_scroll[player_name] = 0
This data is never freed, neither is the data like this. You should make an issue for this, it is not the responsibility of this MR to do maintenance

2021-04-02 23:22 UTC, oversword commented on category.lua
> +end
They are documented now

2021-04-02 23:30 UTC, oversword commented
@SmallJoker 
> Also: Are the textures png-crushed/optipng'd yet?

They are now

2021-04-03 02:16 UTC, oversword commented on default-categories.lua
> +	"default:sword_diamond",
Option added and most of the logic suggested has been implemented

2021-04-03 02:18 UTC, oversword commented on default-categories.lua
> +	"default:cave_ice",
Add liquid sources and biome nodes, not sure about decorations, most of those belong in "plants"

2021-04-03 03:41 UTC, VanessaE commented on callbacks.lua
> +	unified_inventory.current_category_scroll[player_name] = 0
Considering that we're only talking about a couple dozen bytes per user who's joined since startup, I think this can be ignored.  Any decent admin will have a periodic reboot/backup cycle in place, so leak this may be, but it'll never have time to accumulate into anything problematic.

2021-04-03 03:46 UTC, VanessaE commented on default-categories.lua
> +	"default:cave_ice",
Assuming "environment" means the base terrain, then if you only go by those three definitions, then some items in Plantlife modpack would get missed, such as sticks on the ground, or woodsoils under some trees.  That's just an example, since of course I can just add things to that category
 myself.

2021-04-03 03:49 UTC, oversword commented on callbacks.lua
> +	unified_inventory.current_category_scroll[player_name] = 0
I agree vanessa, and considering this will be (at most) in the magnitude of 100s of users - and not thousands of nodes, or tens of thousands of interactions - it really wont be that much data

2021-04-03 03:56 UTC, VanessaE commented on internal.lua
> +			and def.description ~= ""
Acknowledging that those aren't one of @oversword's changes, the `not_in...` lines could be replaced with a check using `minetest.get_item_group()`, and the `description` lines are needed because while an empty string is distinct from one that's `nil`/unset, both have the same meaning to UI (that is, such items are considered broken and thus not shown).

However, since you use the group and description test at least three times with identical code, they should be moved to a function.

2021-04-03 04:26 UTC, oversword commented on internal.lua
> +			and def.description ~= ""
It already has been @VanessaE , see line 287

2021-04-03 04:52 UTC, VanessaE commented on internal.lua
> +			and def.description ~= ""
Oh ok, Github didn't show me that.

2021-04-03 08:21 UTC, SmallJoker commented on internal.lua
> +		formspec[n] = formspec_button(ui_peruser, "next_category", "ui_right_icon.png", categories_scroll_pos, {ui_peruser.pagecols - 1, 0}, 0.8, "Scroll Categories Right")
Whereas they are marked for translation, the script that collects the translation strings only does a static file analysis, hence cannot pick up dynamically typed translations. `S("")` must be used directly where the translation string is.

2021-04-03 08:28 UTC, SmallJoker commented on default-categories.lua
> +	"default:sword_diamond",
> Hard coding these items is no issue because they all appear in the base game

Yes but I wish this mod would also be usable in games other than Minetest Game, and with more mods than what's provided by default. At least I wouldn't want to maintain this list for each and every existing mod, hence automation seems like a pretty good compromise.
If you are keen on maintaining that list of nodes, feel free to keep them hardcoded. Otherwise it would be better to trim it to the exceptional cases or remove entirely because commented code provides exactly no help and is very likely to be removed anyway sooner or later.
Thank you for the changes so far.

2021-04-03 08:32 UTC, SmallJoker commented on category.lua
> +		return a.index < b.index
Do you know that in Lua this comparison works on strings too? There's no need to invent a byte format.

2021-04-03 08:36 UTC, SmallJoker commented on default-categories.lua
> +					   ) then
Which edge-case does this cover?

2021-04-03 11:17 UTC, oversword commented on default-categories.lua
> +					   ) then
This covers the main case, while looking through the data I never saw any doors with `groups = { door = 1 }`, I'm not quite sure what you were referring to with that but I stuck it in there anyways.

2021-04-03 11:23 UTC, oversword commented on category.lua
> +		return a.index < b.index
However, it does not work when comparing strings to numbers. The `index` must be of one type, people will expect that type to be a number, so they must all be converted to numbers

2021-04-03 11:36 UTC, oversword commented on default-categories.lua
> +					   ) then
I see it now, it looks like `door = 1` is only on trapdoors, not 1x2 vertical doors. I can remove the trapdoor condition but I don't see the need

2021-04-03 11:44 UTC, oversword commented on internal.lua
> +		formspec[n] = formspec_button(ui_peruser, "next_category", "ui_right_icon.png", categories_scroll_pos, {ui_peruser.pagecols - 1, 0}, 0.8, "Scroll Categories Right")
Well that is awful... I'll make the change

2021-04-03 11:56 UTC, oversword commented on internal.lua
> +		formspec[n] = formspec_button(ui_peruser, "next_category", "ui_right_icon.png", categories_scroll_pos, {ui_peruser.pagecols - 1, 0}, 0.8, "Scroll Categories Right")
Okay each static string has been wrapped in `S()` instead of trying to it automatically

2021-04-03 13:10 UTC, oversword commented on default-categories.lua
> +	"default:sword_diamond",
I would much rather maintain a hard coded list than a lot of weird logic, it was much faster to just dump a list of items and copy & paste them into categories than it was to trawl through data looking for commonalities - configuration should be manual, not automatic

2021-04-05 17:09 UTC, SmallJoker commented
Lint needs fixing.

PS: I'm personally not motivated in this huge PR, as IMO sorting by group names (in a dropdown box) would've been a much simpler approach, resulting in only a few new code lines. However, since the work is already done and VE seems to like it, I'll go ahead merging as soon the code style issues reported by luacheck are solved.

2021-04-05 17:59 UTC, oversword commented
> Lint needs fixing.

There are no valid linting errors:

- The issue with whitespace on line 57 seems to be an error, I have not changes line 57 and there is no whitespace, vanessa's response re: line 57
  > Yeah I saw that warning and disregarded it. The linter can go ge.....ahem, can be safely ignored in this case
- The other error is `accessing undefined variable doors`, this has been added to the `.luacheckrc`, but since the check script pulls that from `https://raw.githubusercontent.com/minetest-mods/unified_inventory/master/.luacheckrc` this check will fail until the PR is merged. The doors mod is not a dependency of this mod since it's only accessed inside a `minetest.register_on_mods_loaded` callback, an I'm checking if it exists first - so, the mod will be loaded and if it's not there it's fine.

2021-04-05 18:07 UTC, merged