added optional confirmation dialog before clearing inventory
minetest-mods/unified_inventory pull request #172
Opened 2021-04-08 14:08 UTC by uprince

<img width="774" alt="Screenshot 2021-04-08 at 12 13 18" src="https://user-images.githubusercontent.com/9484563/114040575-090ec500-9884-11eb-8cb4-f57528173596.png">

- has no effect unless minetest.conf contains `unified_inventory_clear_inventory_confirm = true`
- relevant code moved to new `clear_inventory.lua` file

2021-04-08 16:47 UTC, SmallJoker commented
This is now a Minetest feature: `/clearinv`. I think this button should only be added when the player is in creative mode. In survival this button is surely unused, and if a player *really" wants to clear the inventory they can simply execute the command.

2021-04-09 09:42 UTC, uprince commented
@SmallJoker, thank you for the comment, and for pointing out the `/clearinv` command.

Our use-case is the following:
- Some of our users are novices in minetest.
- They are playing in creative mode, per our game scenario.
- They often mistakenly empty their inventory by clicking the `clear_inv` button.

After the complaint has come up several times, we felt the need for such a confirmation dialog.

2021-04-09 10:53 UTC, SmallJoker commented
But if they're in creative mode, then it's not a problem? They can correct their mistake quickly.

2021-04-15 16:18 UTC, SmallJoker commented on clear_inventory.lua
> +		end
`string.match` call is superflious. Just perform a simple array check like so `if fields["clear_inv_confirm"] then (stuff) end`

2021-04-15 16:19 UTC, SmallJoker commented on clear_inventory.lua
> +				.."\nUse the trash slot instead."))
I think this can be removed now because the dialogue is supposed to avoid it.

2021-04-15 16:19 UTC, SmallJoker commented on clear_inventory.lua
> +				"image_button[6,2;1.5,1.5;ui_no.png;clear_inv_cancel;]"
Please add labels to clarify the actions

2021-04-15 16:20 UTC, SmallJoker commented on clear_inventory.lua
> +				"image_button[6,2;1.5,1.5;ui_no.png;clear_inv_cancel;]"
Please add labels to clarify the actions.

2021-04-15 16:22 UTC, SmallJoker commented on clear_inventory.lua
> +print("bool :", minetest.settings:get_bool("unified_inventory_clear_inventory_confirm"))
Unnecessary. If you think this is really needed, please use `minetest.log`  and provide information about the source of this message (i.e. `unified_inventory`) and what it's supposed to show.

2021-04-15 16:23 UTC, SmallJoker commented on clear_inventory.lua
> +	if not ui.is_creative(player_name) then
```suggestion
local do_confirm = minetest.settings:get_bool("unified_inventory_clear_inventory_confirm")

local function clear_inventory(player)
	local player_name = player:get_player_name()
	if not ui.is_creative(player_name) and not do_confirm then
```

2022-03-22 08:15 UTC, appgurueu requested changes

2022-03-22 08:15 UTC, appgurueu commented on clear_inventory.lua
> +		minetest.chat_send_player(player_name,
I don't like (1) using chat for this and (2) showing a button in the first place if it is disabled entirely.

2022-03-22 08:15 UTC, appgurueu commented on clear_inventory.lua
> +	minetest.chat_send_player(player_name, S('Inventory cleared!'))
Please use double quotes.

2022-03-22 08:15 UTC, appgurueu commented on clear_inventory.lua
> +				"label[1,1;" .. S("Clear inventory") .. " ?]" ..
Question mark should be part of the translation string (questions might be worded differently in other languages). There should be no space before it.

2022-03-22 08:15 UTC, appgurueu commented on clear_inventory.lua
> +		end
"Hash" check, why not make it `fields.clear_inv_confirm`? Definitely agreed though, linearly searching the fields *and* using `match` is absolutely unnecessary here.

2022-03-22 08:15 UTC, appgurueu commented on clear_inventory.lua
> +ui.register_button("clear_inv", clear_inv_button)
Just don't register the button here if it's disabled entirely. Also saves you the huge `if`.

2022-09-15 08:59 UTC, SmallJoker commented
No activity in months. Please re-open this PR (or ask to, if you can't) when you'd like to address the comments above.

2022-09-15 08:59 UTC, closed without merging